# Identity Service - Development Profile
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hungerbox_identity
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

# OTP Configuration
otp:
  expiration: 300
  length: 6
