# Identity Service - Production Profile
server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hungerbox_identity
    username: hbadmin
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

# OTP Configuration
otp:
  expiration: 300
  length: 6

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
